# Generated by Django 3.2.8 on 2021-10-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangoapp', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
